spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.address}/auth/realms/cydeo-dev

keycloak:
  address: http://localhost:8080

server:
  port: 8762

eureka:
  instance:
    preferIpAddress: true
    ipAddress: 127.0.0.1
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
  context-path: http://localhost:${server.port}/actuator

info:
  application:
    name: gateway-service
    description: Ticketing Application Gateway Service